//! Protobuf-generated message types for Rust↔Python IPC.
//!
//! These types correspond to the definitions in `proto/atlas.proto` and are
//! used for serialising structured data (semantic labels, risk assessments,
//! spatial queries) across the IPC boundary.  Raw Gaussian frame data is
//! transferred via the faster memory-mapped path in [`crate::shared_mem`].
//!
//! # Usage
//!
//! ```no_run
//! use atlas_core::proto::{SemanticLabel, Point3};
//! use prost::Message;
//!
//! let label = SemanticLabel {
//!     object_id: 1,
//!     label: "cup".to_string(),
//!     material: "ceramic".to_string(),
//!     mass_kg: 0.3,
//!     fragility: 0.8,
//!     friction: 0.5,
//!     confidence: 0.95,
//!     position: Some(Point3 { x: 1.0, y: 0.0, z: 0.5 }),
//! };
//!
//! let encoded = label.encode_to_vec();
//! let decoded = SemanticLabel::decode(encoded.as_slice()).unwrap();
//! assert_eq!(decoded.label, "cup");
//! ```

// Generated by prost-build from proto/atlas.proto.
include!(concat!(env!("OUT_DIR"), "/atlas.rs"));
