/**
 * Product playbooks for repeatable ATLAS-0 beta loops.
 */

export const SAFETY_MISSIONS = [
  {
    id: 'cord-safari',
    title: 'Cable safari',
    badge: 'Pet',
    audienceMode: 'pet',
    roomLabel: 'Cable safari',
    copy: 'Hunt for tempting cords, charger loops, and low wires that pets or feet can catch.',
    uploadHint: 'Record low shelves, desk corners, chargers, and floor paths where cords cross walking space.',
    winLabel: 'Cord path checked',
    resultPrompt: 'Share the cord path that got cleaned up, then rescan if the room label is reused.',
    steps: ['Start at floor height near outlets.', 'Pause on desks, TV stands, and charging corners.', 'Look for one cord you can route or tuck away.'],
  },
  {
    id: 'toddler-reach-test',
    title: 'Toddler reach test',
    badge: 'Parent',
    audienceMode: 'toddler',
    roomLabel: 'Toddler reach test',
    copy: 'Scan everything below counter height and ask, "what could a small hand pull, climb, or tip?"',
    uploadHint: 'Keep low tables, shelves, handles, cords, and climbable furniture in frame for a steady moment.',
    winLabel: 'Reach zone reviewed',
    resultPrompt: 'Fix one reachable item first, then rescan from the same low angle for a satisfying before/after.',
    steps: ['Walk the room from a lower angle.', 'Pause on reachable drawers, cords, and unstable furniture.', 'Fix or move one easy object after the report.'],
  },
  {
    id: 'renter-move-in-pass',
    title: 'Move-in receipt',
    badge: 'Renter',
    audienceMode: 'renter',
    roomLabel: 'Move-in receipt',
    copy: 'Make a quick evidence-backed room note before moving furniture, boxes, or pets through the space.',
    uploadHint: 'Record walls, floors, corners, fixtures, and any existing hazards you may want documented.',
    winLabel: 'Move-in evidence saved',
    resultPrompt: 'Download the PDF if the report includes anything worth saving before the room changes.',
    steps: ['Scan each wall and corner slowly.', 'Capture fixtures, floor edges, and existing damage.', 'Download the PDF if the report finds anything worth saving.'],
  },
  {
    id: 'fall-zone-five',
    title: 'Five-minute fall zone',
    badge: 'Quick fix',
    audienceMode: 'general',
    roomLabel: 'Fall zone',
    copy: 'Find one thing that could fall, tip, slide, or break if bumped during a busy day.',
    uploadHint: 'Record shelves, counters, tall furniture, and narrow walk paths where bumps are likely.',
    winLabel: 'Fall zone checked',
    resultPrompt: 'Pick the smallest stabilization fix first and rescan when the room feels calmer.',
    steps: ['Start with the tallest furniture.', 'Pause on shelves and counter edges.', 'Pick one quick stabilization fix.'],
  },
  {
    id: 'guest-ready-scan',
    title: 'Guest-ready sweep',
    badge: 'Home',
    audienceMode: 'general',
    roomLabel: 'Guest-ready sweep',
    copy: 'Before people come over, check the obvious trip paths and fragile surfaces once.',
    uploadHint: 'Record doorways, rug edges, coffee tables, walk paths, and anything fragile near elbows or bags.',
    winLabel: 'Guest path cleared',
    resultPrompt: 'Copy the room win after clearing one trip path or fragile edge before guests arrive.',
    steps: ['Walk the path a guest would take.', 'Pause on rugs, low tables, and doorways.', 'Remove one trip or bump hazard before guests arrive.'],
  },
  {
    id: 'shelf-anchor-check',
    title: 'Shelf anchor check',
    badge: 'Stability',
    audienceMode: 'general',
    roomLabel: 'Shelf anchor check',
    copy: 'Look for tall shelves, bookcases, TV stands, and stacked storage that could tip or slide.',
    uploadHint: 'Pause on tall furniture bases, wall contact points, heavy upper shelves, and nearby traffic paths.',
    winLabel: 'Tall furniture reviewed',
    resultPrompt: 'Use the top action to decide whether a wall anchor, lighter top shelf, or relocation comes first.',
    steps: ['Start with the tallest object in the room.', 'Keep the base and top in frame.', 'Check whether the report calls out tipping or heavy-top risks.'],
  },
  {
    id: 'hallway-trip-path',
    title: 'Hallway trip path',
    badge: 'Trip path',
    audienceMode: 'general',
    roomLabel: 'Hallway trip path',
    copy: 'Sweep the path people actually walk and find clutter, cords, rug edges, or narrow squeeze points.',
    uploadHint: 'Record from doorway to doorway, keeping the floor path and side obstacles visible.',
    winLabel: 'Walk path checked',
    resultPrompt: 'Clear one path issue and rescan the same hallway to make the before/after obvious.',
    steps: ['Walk the exact path someone takes.', 'Keep the floor centered.', 'Pause on rugs, thresholds, cords, and clutter.'],
  },
  {
    id: 'kitchen-counter-sweep',
    title: 'Kitchen counter sweep',
    badge: 'Kitchen',
    audienceMode: 'general',
    roomLabel: 'Kitchen counter sweep',
    copy: 'Check counter edges, appliance cords, fragile items, and spill-prone clutter before a busy cooking session.',
    uploadHint: 'Record counters, appliance corners, dangling cords, sink area, and common walking paths.',
    winLabel: 'Counter risk reviewed',
    resultPrompt: 'Move one edge item or cord first, then copy the room win for the person sharing the kitchen.',
    steps: ['Start at the main prep counter.', 'Pause on appliance cords and edge items.', 'Scan the floor path between sink, stove, and fridge.'],
  },
  {
    id: 'plant-and-glass-pass',
    title: 'Plant and glass pass',
    badge: 'Fragile',
    audienceMode: 'pet',
    roomLabel: 'Plant and glass pass',
    copy: 'Find low plants, glass decor, and fragile objects that pets, bags, or elbows could knock over.',
    uploadHint: 'Record plant stands, side tables, low shelves, window ledges, and narrow movement paths.',
    winLabel: 'Fragile zone checked',
    resultPrompt: 'Move one fragile object out of the bump zone and rescan if you want a visible score change.',
    steps: ['Start at low shelves and plant stands.', 'Pause on glass or ceramic items.', 'Check the route pets or people cut through.'],
  },
  {
    id: 'bedtime-floor-reset',
    title: 'Bedtime floor reset',
    badge: 'Night',
    audienceMode: 'general',
    roomLabel: 'Bedtime floor reset',
    copy: 'Do a low-light-aware scan of the floor path so late-night trips are easier to spot.',
    uploadHint: 'Use good lighting for the scan, but focus on floor clutter, slippers, chargers, rugs, and narrow paths.',
    winLabel: 'Night path reset',
    resultPrompt: 'Clear one floor item before bed and mark the challenge complete locally.',
    steps: ['Turn lights on for capture quality.', 'Scan the bed-to-door path.', 'Remove one thing that would be annoying in the dark.'],
  },
];

export const CAPTURE_COACH_MODES = {
  general: {
    title: 'General room safety pass',
    promise: 'Best for a first beta scan when you just want a practical report.',
    route: ['Doorway and main walking path', 'Tall furniture and shelves', 'Tables, counters, and fragile edges', 'Floor-level trip points'],
    checks: ['Lights are on', 'Camera moves slowly', 'All four corners appear', 'Floor path appears', 'Shelves and counters pause in frame'],
    funPrompt: 'Try the "one quick fix" rule: pick one thing you can improve in under five minutes after the report.',
  },
  toddler: {
    title: 'Toddler reach pass',
    promise: 'Weights reachable, climbable, and pullable objects higher.',
    route: ['Low drawers and handles', 'Cords within reach', 'Climbable furniture', 'Heavy objects near edges'],
    checks: ['Camera drops to child height', 'Low surfaces stay visible', 'Cords and handles appear', 'Furniture bases appear', 'Sharp or fragile edges appear'],
    funPrompt: 'Scan from knee height for 20 seconds. It feels silly, but it changes what you notice.',
  },
  pet: {
    title: 'Pet safety sweep',
    promise: 'Highlights floor-level cords, tempting loops, unstable objects, and chewable clutter.',
    route: ['Outlet corners and charger nests', 'Desk and TV stand cables', 'Floor clutter and toys', 'Low shelves and plant stands'],
    checks: ['Camera starts low', 'Cord paths are visible', 'Under-table areas appear', 'Low shelves appear', 'Food/plant areas appear'],
    funPrompt: 'Play "what would a bored pet find first?" and let the scan catch the boring-but-real risks.',
  },
  renter: {
    title: 'Move-in receipt pass',
    promise: 'Keeps the report useful as evidence-backed notes before furniture or boxes change the room.',
    route: ['Each wall and corner', 'Floor edges and transitions', 'Fixtures and outlets', 'Existing scuffs or unsafe areas'],
    checks: ['Room label is specific', 'Walls and fixtures appear', 'Floor edges appear', 'Existing damage is captured', 'PDF export is planned'],
    funPrompt: 'Treat it like a tiny home inventory: one walkthrough now can save confusion later.',
  },
};

export const REPORT_DECISION_STEPS = [
  {
    id: 'fix',
    title: 'Fix one thing',
    copy: 'Start with the top action instead of trying to make the whole room perfect.',
  },
  {
    id: 'verify',
    title: 'Check the evidence',
    copy: 'Use frames and trust notes before acting on weaker findings.',
  },
  {
    id: 'rescan',
    title: 'Rescan the same room',
    copy: 'Reuse the room label so ATLAS-0 can compare the next pass.',
  },
  {
    id: 'share',
    title: 'Share the win',
    copy: 'Copy a clean summary or export the PDF when a fix is done.',
  },
];

export const BETA_SHARE_PROMPTS = [
  'I tried ATLAS-0: upload one room walkthrough, get a hazard report with evidence frames and practical fixes.',
  'Tiny room safety challenge: scan one room, fix one thing, rescan it. ATLAS-0 makes the before/after visible.',
  'ATLAS-0 is a room safety scan for renters, parents, pet owners, and anyone who wants a calmer home check.',
];
