/**
 * Product playbooks for repeatable ATLAS-0 beta loops.
 */

export const SAFETY_MISSIONS = [
  {
    id: 'cord-safari',
    title: 'Cable safari',
    badge: 'Pet',
    audienceMode: 'pet',
    roomLabel: 'Cable safari',
    copy: 'Hunt for tempting cords, charger loops, and low wires that pets or feet can catch.',
    uploadHint: 'Record low shelves, desk corners, chargers, and floor paths where cords cross walking space.',
    winLabel: 'Cord path checked',
    resultPrompt: 'Share the cord path that got cleaned up, then rescan if the room label is reused.',
    steps: ['Start at floor height near outlets.', 'Pause on desks, TV stands, and charging corners.', 'Look for one cord you can route or tuck away.'],
  },
  {
    id: 'toddler-reach-test',
    title: 'Toddler reach test',
    badge: 'Parent',
    audienceMode: 'toddler',
    roomLabel: 'Toddler reach test',
    copy: 'Scan everything below counter height and ask, "what could a small hand pull, climb, or tip?"',
    uploadHint: 'Keep low tables, shelves, handles, cords, and climbable furniture in frame for a steady moment.',
    winLabel: 'Reach zone reviewed',
    resultPrompt: 'Fix one reachable item first, then rescan from the same low angle for a satisfying before/after.',
    steps: ['Walk the room from a lower angle.', 'Pause on reachable drawers, cords, and unstable furniture.', 'Fix or move one easy object after the report.'],
  },
  {
    id: 'renter-move-in-pass',
    title: 'Move-in receipt',
    badge: 'Renter',
    audienceMode: 'renter',
    roomLabel: 'Move-in receipt',
    copy: 'Make a quick evidence-backed room note before moving furniture, boxes, or pets through the space.',
    uploadHint: 'Record walls, floors, corners, fixtures, and any existing hazards you may want documented.',
    winLabel: 'Move-in evidence saved',
    resultPrompt: 'Download the PDF if the report includes anything worth saving before the room changes.',
    steps: ['Scan each wall and corner slowly.', 'Capture fixtures, floor edges, and existing damage.', 'Download the PDF if the report finds anything worth saving.'],
  },
  {
    id: 'fall-zone-five',
    title: 'Five-minute fall zone',
    badge: 'Quick fix',
    audienceMode: 'general',
    roomLabel: 'Fall zone',
    copy: 'Find one thing that could fall, tip, slide, or break if bumped during a busy day.',
    uploadHint: 'Record shelves, counters, tall furniture, and narrow walk paths where bumps are likely.',
    winLabel: 'Fall zone checked',
    resultPrompt: 'Pick the smallest stabilization fix first and rescan when the room feels calmer.',
    steps: ['Start with the tallest furniture.', 'Pause on shelves and counter edges.', 'Pick one quick stabilization fix.'],
  },
  {
    id: 'guest-ready-scan',
    title: 'Guest-ready sweep',
    badge: 'Home',
    audienceMode: 'general',
    roomLabel: 'Guest-ready sweep',
    copy: 'Before people come over, check the obvious trip paths and fragile surfaces once.',
    uploadHint: 'Record doorways, rug edges, coffee tables, walk paths, and anything fragile near elbows or bags.',
    winLabel: 'Guest path cleared',
    resultPrompt: 'Copy the room win after clearing one trip path or fragile edge before guests arrive.',
    steps: ['Walk the path a guest would take.', 'Pause on rugs, low tables, and doorways.', 'Remove one trip or bump hazard before guests arrive.'],
  },
  {
    id: 'shelf-anchor-check',
    title: 'Shelf anchor check',
    badge: 'Stability',
    audienceMode: 'general',
    roomLabel: 'Shelf anchor check',
    copy: 'Look for tall shelves, bookcases, TV stands, and stacked storage that could tip or slide.',
    uploadHint: 'Pause on tall furniture bases, wall contact points, heavy upper shelves, and nearby traffic paths.',
    winLabel: 'Tall furniture reviewed',
    resultPrompt: 'Use the top action to decide whether a wall anchor, lighter top shelf, or relocation comes first.',
    steps: ['Start with the tallest object in the room.', 'Keep the base and top in frame.', 'Check whether the report calls out tipping or heavy-top risks.'],
  },
  {
    id: 'hallway-trip-path',
    title: 'Hallway trip path',
    badge: 'Trip path',
    audienceMode: 'general',
    roomLabel: 'Hallway trip path',
    copy: 'Sweep the path people actually walk and find clutter, cords, rug edges, or narrow squeeze points.',
    uploadHint: 'Record from doorway to doorway, keeping the floor path and side obstacles visible.',
    winLabel: 'Walk path checked',
    resultPrompt: 'Clear one path issue and rescan the same hallway to make the before/after obvious.',
    steps: ['Walk the exact path someone takes.', 'Keep the floor centered.', 'Pause on rugs, thresholds, cords, and clutter.'],
  },
  {
    id: 'kitchen-counter-sweep',
    title: 'Kitchen counter sweep',
    badge: 'Kitchen',
    audienceMode: 'general',
    roomLabel: 'Kitchen counter sweep',
    copy: 'Check counter edges, appliance cords, fragile items, and spill-prone clutter before a busy cooking session.',
    uploadHint: 'Record counters, appliance corners, dangling cords, sink area, and common walking paths.',
    winLabel: 'Counter risk reviewed',
    resultPrompt: 'Move one edge item or cord first, then copy the room win for the person sharing the kitchen.',
    steps: ['Start at the main prep counter.', 'Pause on appliance cords and edge items.', 'Scan the floor path between sink, stove, and fridge.'],
  },
  {
    id: 'plant-and-glass-pass',
    title: 'Plant and glass pass',
    badge: 'Fragile',
    audienceMode: 'pet',
    roomLabel: 'Plant and glass pass',
    copy: 'Find low plants, glass decor, and fragile objects that pets, bags, or elbows could knock over.',
    uploadHint: 'Record plant stands, side tables, low shelves, window ledges, and narrow movement paths.',
    winLabel: 'Fragile zone checked',
    resultPrompt: 'Move one fragile object out of the bump zone and rescan if you want a visible score change.',
    steps: ['Start at low shelves and plant stands.', 'Pause on glass or ceramic items.', 'Check the route pets or people cut through.'],
  },
  {
    id: 'bedtime-floor-reset',
    title: 'Bedtime floor reset',
    badge: 'Night',
    audienceMode: 'general',
    roomLabel: 'Bedtime floor reset',
    copy: 'Do a low-light-aware scan of the floor path so late-night trips are easier to spot.',
    uploadHint: 'Use good lighting for the scan, but focus on floor clutter, slippers, chargers, rugs, and narrow paths.',
    winLabel: 'Night path reset',
    resultPrompt: 'Clear one floor item before bed and mark the challenge complete locally.',
    steps: ['Turn lights on for capture quality.', 'Scan the bed-to-door path.', 'Remove one thing that would be annoying in the dark.'],
  },
];

export const CAPTURE_COACH_MODES = {
  general: {
    title: 'General room safety pass',
    promise: 'Best for a first beta scan when you just want a practical report.',
    route: ['Doorway and main walking path', 'Tall furniture and shelves', 'Tables, counters, and fragile edges', 'Floor-level trip points'],
    checks: ['Lights are on', 'Camera moves slowly', 'All four corners appear', 'Floor path appears', 'Shelves and counters pause in frame'],
    funPrompt: 'Try the "one quick fix" rule: pick one thing you can improve in under five minutes after the report.',
  },
  toddler: {
    title: 'Toddler reach pass',
    promise: 'Weights reachable, climbable, and pullable objects higher.',
    route: ['Low drawers and handles', 'Cords within reach', 'Climbable furniture', 'Heavy objects near edges'],
    checks: ['Camera drops to child height', 'Low surfaces stay visible', 'Cords and handles appear', 'Furniture bases appear', 'Sharp or fragile edges appear'],
    funPrompt: 'Scan from knee height for 20 seconds. It feels silly, but it changes what you notice.',
  },
  pet: {
    title: 'Pet safety sweep',
    promise: 'Highlights floor-level cords, tempting loops, unstable objects, and chewable clutter.',
    route: ['Outlet corners and charger nests', 'Desk and TV stand cables', 'Floor clutter and toys', 'Low shelves and plant stands'],
    checks: ['Camera starts low', 'Cord paths are visible', 'Under-table areas appear', 'Low shelves appear', 'Food/plant areas appear'],
    funPrompt: 'Play "what would a bored pet find first?" and let the scan catch the boring-but-real risks.',
  },
  renter: {
    title: 'Move-in receipt pass',
    promise: 'Keeps the report useful as evidence-backed notes before furniture or boxes change the room.',
    route: ['Each wall and corner', 'Floor edges and transitions', 'Fixtures and outlets', 'Existing scuffs or unsafe areas'],
    checks: ['Room label is specific', 'Walls and fixtures appear', 'Floor edges appear', 'Existing damage is captured', 'PDF export is planned'],
    funPrompt: 'Treat it like a tiny home inventory: one walkthrough now can save confusion later.',
  },
};

export const REPORT_DECISION_STEPS = [
  {
    id: 'fix',
    title: 'Fix one thing',
    copy: 'Start with the top action instead of trying to make the whole room perfect.',
  },
  {
    id: 'verify',
    title: 'Check the evidence',
    copy: 'Use frames and trust notes before acting on weaker findings.',
  },
  {
    id: 'rescan',
    title: 'Rescan the same room',
    copy: 'Reuse the room label so ATLAS-0 can compare the next pass.',
  },
  {
    id: 'share',
    title: 'Share the win',
    copy: 'Copy a clean summary or export the PDF when a fix is done.',
  },
];

export const BETA_SHARE_PROMPTS = [
  'I tried ATLAS-0: upload one room walkthrough, get a hazard report with evidence frames and practical fixes.',
  'Tiny room safety challenge: scan one room, fix one thing, rescan it. ATLAS-0 makes the before/after visible.',
  'ATLAS-0 is a room safety scan for renters, parents, pet owners, and anyone who wants a calmer home check.',
];

export const ROOM_MYSTERY_MODES = [
  {
    id: 'hidden-quick-fix',
    title: 'One fix hiding in plain sight',
    audienceMode: 'general',
    roomLabel: 'Hidden quick fix',
    prompt: 'What is the one small fix this room is quietly asking for?',
    uploadHint: 'Record the normal walking path, shelf edges, tables, cords, and anything that would be annoying if bumped.',
    resultFrame: 'Start with the smallest evidence-backed improvement, then rescan to see whether the room feels calmer.',
  },
  {
    id: 'pet-knockover',
    title: 'What could a pet knock over?',
    audienceMode: 'pet',
    roomLabel: 'Pet curiosity pass',
    prompt: 'What would a bored pet notice first?',
    uploadHint: 'Keep low shelves, plants, dangling cords, side tables, and under-desk corners visible from pet height.',
    resultFrame: 'Look for floor-level temptations and fragile bump zones before they become a mess.',
  },
  {
    id: 'tomorrow-annoyance',
    title: 'What will annoy me tomorrow?',
    audienceMode: 'general',
    roomLabel: 'Tomorrow annoyance pass',
    prompt: 'What tiny room problem is easiest to prevent today?',
    uploadHint: 'Scan doorways, floors, bedside paths, desks, and high-touch surfaces that collect clutter.',
    resultFrame: 'Treat the top finding as a five-minute future-you favor, not a scary warning.',
  },
  {
    id: 'tiny-hands',
    title: 'What can tiny hands reach?',
    audienceMode: 'toddler',
    roomLabel: 'Tiny hands mystery',
    prompt: 'What is reachable, pullable, climbable, or tip-prone below counter height?',
    uploadHint: 'Record from a lower angle and pause on handles, cords, drawers, shelves, and table edges.',
    resultFrame: 'Use this as a calm reach-zone review, not a substitute for active supervision.',
  },
  {
    id: 'guest-route',
    title: 'What would a guest trip over?',
    audienceMode: 'general',
    roomLabel: 'Guest route mystery',
    prompt: 'What does a first-time visitor not know to avoid?',
    uploadHint: 'Walk from entry to seating, keeping rug edges, bags, cords, thresholds, and low tables in frame.',
    resultFrame: 'Clear the easiest path issue first, then share the room win if someone else should know.',
  },
];

export const CURIOSITY_SAMPLE_GALLERY = [
  {
    id: 'sample-toddler-room',
    title: 'Toddler reach room',
    audienceMode: 'toddler',
    roomLabel: 'Toddler reach sample',
    lesson: 'See how ATLAS-0 frames reachable objects without pretending the room is certified safe.',
  },
  {
    id: 'sample-pet-corner',
    title: 'Pet corner sweep',
    audienceMode: 'pet',
    roomLabel: 'Pet corner sample',
    lesson: 'Preview cord, plant, and low-shelf language before scanning a real pet route.',
  },
  {
    id: 'sample-renter-move-in',
    title: 'Renter move-in note',
    audienceMode: 'renter',
    roomLabel: 'Move-in sample',
    lesson: 'Use the sample as a model for evidence-backed room notes you can export.',
  },
  {
    id: 'sample-guest-ready',
    title: 'Guest-ready living room',
    audienceMode: 'general',
    roomLabel: 'Guest-ready sample',
    lesson: 'Learn how trip paths and fragile edges become a simple fix-first brief.',
  },
  {
    id: 'sample-night-path',
    title: 'Night path reset',
    audienceMode: 'general',
    roomLabel: 'Night path sample',
    lesson: 'See how one floor-path scan can turn into a calm before-bed room win.',
  },
];

export const ROOM_PLAYBOOKS = [
  {
    id: 'baby-visit-prep',
    title: 'Baby visit prep',
    badge: 'Soft landing',
    audienceMode: 'toddler',
    roomLabel: 'Baby visit room',
    mysteryModeId: 'tiny-hands',
    ritualId: 'tiny-hands-sweep',
    captureFocus: 'Move from the doorway to low shelves, coffee tables, cords, corners, and anything reachable below waist height.',
    prompt: 'What would a small visitor reach before an adult notices?',
    shareAngle: 'Family summary',
  },
  {
    id: 'pet-chaos-check',
    title: 'Pet chaos check',
    badge: 'Paws first',
    audienceMode: 'pet',
    roomLabel: 'Pet corner',
    mysteryModeId: 'pet-knockover',
    ritualId: 'pet-calm-corner',
    captureFocus: 'Hold on floor-level clutter, dangling cords, plant stands, bowls, and anything a pet could bump or chew.',
    prompt: 'What could a curious pet knock over, chew, or drag into the path?',
    shareAngle: 'Quick room win',
  },
  {
    id: 'renter-move-in-proof',
    title: 'Renter move-in proof',
    badge: 'Receipt ready',
    audienceMode: 'renter',
    roomLabel: 'Move-in room',
    mysteryModeId: 'hidden-quick-fix',
    ritualId: 'renter-proof-note',
    captureFocus: 'Pan slowly across entry paths, shelves, fixtures, cords, prior damage, loose items, and places you may want documented.',
    prompt: 'What should be documented before boxes and furniture make the room harder to read?',
    shareAngle: 'Landlord summary',
  },
  {
    id: 'night-path-reset',
    title: 'Night path reset',
    badge: 'Low light',
    audienceMode: 'general',
    roomLabel: 'Night path',
    mysteryModeId: 'tomorrow-annoyance',
    ritualId: 'morning-path-reset',
    captureFocus: 'Trace the path from bed or sofa to doorway, bathroom, kitchen, and switches. Pause on rugs, cords, baskets, and sharp corners.',
    prompt: 'What would annoy or trip me when I am half awake tomorrow?',
    shareAngle: 'Private PDF wording',
  },
  {
    id: 'guest-ready-scan',
    title: 'Guest-ready scan',
    badge: 'Hospitality',
    audienceMode: 'general',
    roomLabel: 'Guest-ready room',
    mysteryModeId: 'guest-route',
    ritualId: 'morning-path-reset',
    captureFocus: 'Show the first path a guest walks, seating edges, bags/storage zones, rugs, plants, side tables, and anything that could tip.',
    prompt: 'What would a guest notice, bump, or need explained?',
    shareAngle: 'Family summary',
  },
];

export const ROOM_RITUALS = [
  {
    id: 'morning-path-reset',
    title: 'Morning path reset',
    cadence: 'Daily',
    audienceMode: 'general',
    roomLabel: 'Morning path reset',
    season: 'Everyday',
    duration: '5 min',
    copy: 'Start with the path from bed, door, kitchen, or desk. Clear one thing that would annoy you later.',
    prompt: 'Fix today: clear the first floor or doorway obstacle the report calls out.',
    icon: 'sun',
  },
  {
    id: 'pet-calm-corner',
    title: 'Pet calm corner',
    cadence: 'Daily',
    audienceMode: 'pet',
    roomLabel: 'Pet calm corner',
    season: 'Everyday',
    duration: '4 min',
    copy: 'Check cords, low plants, food corners, and tempting shelf edges from pet height.',
    prompt: 'Fix today: move one chewable, dangling, or fragile thing out of the pet route.',
    icon: 'paw',
  },
  {
    id: 'tiny-hands-sweep',
    title: 'Tiny hands sweep',
    cadence: 'Weekly',
    audienceMode: 'toddler',
    roomLabel: 'Tiny hands sweep',
    season: 'Family',
    duration: '6 min',
    copy: 'Scan below counter height and ask what could be pulled, climbed, opened, or tipped.',
    prompt: 'Fix today: lower the risk around one reachable handle, edge, or heavy object.',
    icon: 'hand',
  },
  {
    id: 'renter-proof-note',
    title: 'Renter proof note',
    cadence: 'Monthly',
    audienceMode: 'renter',
    roomLabel: 'Renter proof note',
    season: 'Move-in',
    duration: '7 min',
    copy: 'Make a calm room note before furniture, guests, repairs, or move-out changes the space.',
    prompt: 'Fix today: export the PDF if the scan captures something worth documenting.',
    icon: 'key',
  },
];

export const SEASONAL_RITUAL_PACKS = [
  {
    id: 'monsoon-entryway',
    title: 'Monsoon entryway pack',
    season: 'Rainy day',
    audienceMode: 'general',
    roomLabel: 'Monsoon entryway',
    ritualId: 'morning-path-reset',
    copy: 'Watch for wet floor paths, shoes near doors, chargers on the floor, and slippery thresholds.',
  },
  {
    id: 'festival-guest-ready',
    title: 'Guest-ready festival pack',
    season: 'Hosting',
    audienceMode: 'general',
    roomLabel: 'Guest-ready festival room',
    ritualId: 'morning-path-reset',
    copy: 'Check crowd paths, fragile decor, low tables, candles, cords, and bags near walkways.',
  },
  {
    id: 'summer-cord-heat',
    title: 'Summer cord and heat pack',
    season: 'Heat',
    audienceMode: 'pet',
    roomLabel: 'Summer cord check',
    ritualId: 'pet-calm-corner',
    copy: 'Scan fans, extension cords, chargers, plants, and clutter near warm electronics.',
  },
  {
    id: 'winter-night-path',
    title: 'Winter night path pack',
    season: 'Night reset',
    audienceMode: 'general',
    roomLabel: 'Winter night path',
    ritualId: 'morning-path-reset',
    copy: 'Look for blankets, slippers, heater cords, rugs, and low-light path issues before bedtime.',
  },
  {
    id: 'moving-day-proof',
    title: 'Moving day proof pack',
    season: 'Move',
    audienceMode: 'renter',
    roomLabel: 'Moving day proof',
    ritualId: 'renter-proof-note',
    copy: 'Document floor paths, fixtures, loose shelves, and existing hazards before boxes change the room.',
  },
  {
    id: 'new-pet-week',
    title: 'New pet week pack',
    season: 'Pet',
    audienceMode: 'pet',
    roomLabel: 'New pet week',
    ritualId: 'pet-calm-corner',
    copy: 'Scan low shelves, chewable cords, plants, bins, and tempting corners from pet height.',
  },
  {
    id: 'baby-visit-weekend',
    title: 'Baby visit weekend pack',
    season: 'Family',
    audienceMode: 'toddler',
    roomLabel: 'Baby visit weekend',
    ritualId: 'tiny-hands-sweep',
    copy: 'Check reachable objects, table edges, cords, handles, and climbable furniture before visitors arrive.',
  },
];

export const ROOM_PERSONALITIES = [
  {
    id: 'calm-caretaker',
    title: 'Calm caretaker',
    badge: 'Steady',
    match: ['low', 'calm', 'guest', 'living'],
    copy: 'This room reads like a steady home base: keep the main path clear and rescan after small resets.',
    nextPrompt: 'Pick one surface or path to keep easy for the next check.',
  },
  {
    id: 'curious-corner',
    title: 'Curious corner',
    badge: 'Pet aware',
    match: ['pet', 'cord', 'plant', 'corner'],
    copy: 'This room has the kind of low, tempting details pets and feet tend to discover first.',
    nextPrompt: 'Start with cords, plants, and low fragile objects before rescanning.',
  },
  {
    id: 'tiny-hands-zone',
    title: 'Tiny-hands zone',
    badge: 'Reach zone',
    match: ['toddler', 'baby', 'reach', 'nursery'],
    copy: 'This room benefits from a lower camera angle and a reach-first mindset.',
    nextPrompt: 'Check handles, cords, heavy objects, and climbable edges from knee height.',
  },
  {
    id: 'proof-keeper',
    title: 'Proof keeper',
    badge: 'Renter',
    match: ['renter', 'move', 'proof', 'receipt'],
    copy: 'This room is useful as a before/after record, especially before furniture or repairs change it.',
    nextPrompt: 'Reuse the same label and export the PDF when the evidence is worth keeping.',
  },
  {
    id: 'reset-needed',
    title: 'Reset needed',
    badge: 'Watch',
    match: ['rescan', 'trip', 'fall', 'unstable', 'high'],
    copy: 'This room is asking for a focused follow-up: fix one visible issue, then scan the same route again.',
    nextPrompt: 'Use the same room label so the next report can compare progress.',
  },
];

export const PERSONAL_SAFETY_MODES = [
  {
    id: 'elderly-parent-visit',
    title: 'Elderly parent visit',
    audienceMode: 'general',
    roomLabel: 'Parent visit path',
    mysteryModeId: 'guest-route',
    captureFocus: 'Keep the walking path, rug edges, cords, chair legs, bathroom route, and lighting transitions visible.',
    copy: 'A gentle path-first scan for trip points, reach issues, and awkward room transitions.',
  },
  {
    id: 'roommate-move-in',
    title: 'Roommate move-in',
    audienceMode: 'renter',
    roomLabel: 'Roommate move-in',
    mysteryModeId: 'hidden-quick-fix',
    captureFocus: 'Document shared paths, fixtures, shelves, outlets, floor transitions, and anything fragile near move-in traffic.',
    copy: 'A shared-space receipt before furniture, bags, and new habits change the room.',
  },
  {
    id: 'airbnb-guest-reset',
    title: 'Airbnb / guest reset',
    audienceMode: 'general',
    roomLabel: 'Guest reset',
    mysteryModeId: 'guest-route',
    captureFocus: 'Record entry paths, suitcase zones, low tables, outlets, rugs, decor, and anything guests may bump.',
    copy: 'A host-friendly scan for clear paths, fragile edges, and guest confusion points.',
  },
  {
    id: 'new-puppy',
    title: 'New puppy',
    audienceMode: 'pet',
    roomLabel: 'New puppy room',
    mysteryModeId: 'pet-knockover',
    captureFocus: 'Start low and pause on cords, bins, low plants, food areas, under-table corners, and chewable objects.',
    copy: 'A floor-level pass for the delightful chaos of a curious new pet.',
  },
  {
    id: 'baby-crawling-soon',
    title: 'Baby crawling soon',
    audienceMode: 'toddler',
    roomLabel: 'Crawling soon room',
    mysteryModeId: 'tiny-hands',
    captureFocus: 'Scan from low height and keep drawers, handles, cords, table edges, shelves, and furniture bases in frame.',
    copy: 'A reach-zone scan before the room starts getting explored from the floor.',
  },
  {
    id: 'party-cleanup',
    title: 'Party cleanup',
    audienceMode: 'general',
    roomLabel: 'Party cleanup path',
    mysteryModeId: 'tomorrow-annoyance',
    captureFocus: 'Show bags, bottles, chargers, rugs, low tables, seating edges, and the first path people will walk tomorrow.',
    copy: 'A next-morning reset for clutter, trip points, and fragile leftovers.',
  },
  {
    id: 'home-office-cable-reset',
    title: 'Home office cable reset',
    audienceMode: 'pet',
    roomLabel: 'Home office cable reset',
    mysteryModeId: 'hidden-quick-fix',
    captureFocus: 'Pause on outlet nests, desk underside, chargers, monitor cables, chair path, and floor-level loops.',
    copy: 'A workday-friendly check for cords, rolling-chair paths, and charger clutter.',
  },
];

export const REPORT_THEMES = [
  {
    id: 'calm-brief',
    title: 'Calm Brief',
    badge: 'Default',
    copy: 'Short, calm, action-first language for personal review.',
  },
  {
    id: 'family-note',
    title: 'Family Note',
    badge: 'Share',
    copy: 'Plain-language summary for partners, parents, roommates, or guests.',
  },
  {
    id: 'renter-proof',
    title: 'Renter Proof',
    badge: 'Record',
    copy: 'More evidence-oriented wording for move-in, repair, or landlord conversations.',
  },
  {
    id: 'pet-check',
    title: 'Pet Check',
    badge: 'Paws',
    copy: 'Frames findings around low, chewable, bumpable, and tempting objects.',
  },
  {
    id: 'guest-ready',
    title: 'Guest Ready',
    badge: 'Host',
    copy: 'Highlights walk paths, fragile edges, and what a visitor may not know to avoid.',
  },
];

export const HOME_BINGO_TASKS = [
  { id: 'scan-hallway', title: 'Scan a hallway', copy: 'Check the route people walk without thinking.' },
  { id: 'clear-cord', title: 'Clear one cord', copy: 'Move, tuck, or route one cable out of a path.' },
  { id: 'rescan-room', title: 'Rescan a room', copy: 'Reuse the same room label after a small fix.' },
  { id: 'copy-room-win', title: 'Copy a room win', copy: 'Share one calm, specific improvement.' },
  { id: 'complete-fix-quest', title: 'Complete one Fix Quest', copy: 'Turn a report item into a small home win.' },
  { id: 'try-playbook', title: 'Try a playbook', copy: 'Use a room story before upload.' },
  { id: 'open-journal', title: 'Open Home Journal', copy: 'Check the last room you saved locally.' },
  { id: 'seasonal-pack', title: 'Pick a seasonal pack', copy: 'Use a timely scan lens for the room.' },
  { id: 'personal-mode', title: 'Pick a personal mode', copy: 'Scan for a real-life moment coming up.' },
];

export const FIX_QUEST_TEMPLATES = [
  {
    id: 'path-clear',
    label: 'Path clear',
    copy: 'Make one walking path easier before rescanning.',
  },
  {
    id: 'edge-reset',
    label: 'Edge reset',
    copy: 'Move one object away from a table, shelf, or counter edge.',
  },
  {
    id: 'cord-tuck',
    label: 'Cord tuck',
    copy: 'Route one cord so feet, pets, or wheels are less likely to catch it.',
  },
  {
    id: 'fragile-lift',
    label: 'Fragile lift',
    copy: 'Move one fragile object out of the normal bump zone.',
  },
  {
    id: 'rescan-proof',
    label: 'Rescan proof',
    copy: 'Repeat the same route and room label to verify the change.',
  },
];
