# ruff: noqa
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: atlas.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "atlas.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x61tlas.proto\x12\x05\x61tlas")\n\x06Point3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02"W\n\x04Pose\x12\x1f\n\x08position\x18\x01 \x01(\x0b\x32\r.atlas.Point3\x12\n\n\x02qw\x18\x02 \x01(\x02\x12\n\n\x02qx\x18\x03 \x01(\x02\x12\n\n\x02qy\x18\x04 \x01(\x02\x12\n\n\x02qz\x18\x05 \x01(\x02"\x88\x01\n\x08Gaussian\x12\x1d\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\r.atlas.Point3\x12\x12\n\ncovariance\x18\x02 \x03(\x02\x12\x17\n\x0fsh_coefficients\x18\x03 \x03(\x02\x12\x0f\n\x07opacity\x18\x04 \x01(\x02\x12\r\n\x05scale\x18\x05 \x03(\x02\x12\x10\n\x08rotation\x18\x06 \x03(\x02"x\n\x08MapShard\x12\x10\n\x08shard_id\x18\x01 \x01(\x04\x12"\n\tgaussians\x18\x02 \x03(\x0b\x32\x0f.atlas.Gaussian\x12 \n\x0b\x63\x61mera_pose\x18\x03 \x01(\x0b\x32\x0b.atlas.Pose\x12\x14\n\x0ctimestamp_ns\x18\x04 \x01(\x04"\xae\x01\n\rSemanticLabel\x12\x11\n\tobject_id\x18\x01 \x01(\x04\x12\r\n\x05label\x18\x02 \x01(\t\x12\x10\n\x08material\x18\x03 \x01(\t\x12\x0f\n\x07mass_kg\x18\x04 \x01(\x02\x12\x11\n\tfragility\x18\x05 \x01(\x02\x12\x10\n\x08\x66riction\x18\x06 \x01(\x02\x12\x12\n\nconfidence\x18\x07 \x01(\x02\x12\x1f\n\x08position\x18\x08 \x01(\x0b\x32\r.atlas.Point3"\x85\x01\n\x0eRiskAssessment\x12\x11\n\tobject_id\x18\x01 \x01(\x04\x12\x11\n\trisk_type\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\x02\x12#\n\x0cimpact_point\x18\x04 \x01(\x0b\x32\r.atlas.Point3\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t"\x8d\x01\n\nSceneState\x12%\n\x07objects\x18\x01 \x03(\x0b\x32\x14.atlas.SemanticLabel\x12$\n\x05risks\x18\x02 \x03(\x0b\x32\x15.atlas.RiskAssessment\x12 \n\x0b\x63\x61mera_pose\x18\x03 \x01(\x0b\x32\x0b.atlas.Pose\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\x04\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "atlas_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_POINT3"]._serialized_start = 22
    _globals["_POINT3"]._serialized_end = 63
    _globals["_POSE"]._serialized_start = 65
    _globals["_POSE"]._serialized_end = 152
    _globals["_GAUSSIAN"]._serialized_start = 155
    _globals["_GAUSSIAN"]._serialized_end = 291
    _globals["_MAPSHARD"]._serialized_start = 293
    _globals["_MAPSHARD"]._serialized_end = 413
    _globals["_SEMANTICLABEL"]._serialized_start = 416
    _globals["_SEMANTICLABEL"]._serialized_end = 590
    _globals["_RISKASSESSMENT"]._serialized_start = 593
    _globals["_RISKASSESSMENT"]._serialized_end = 726
    _globals["_SCENESTATE"]._serialized_start = 729
    _globals["_SCENESTATE"]._serialized_end = 870
# @@protoc_insertion_point(module_scope)
